# Generated by Django 5.0.2 on 2024-03-30 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_alter_parcel_courier_alter_parcel_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
