# Generated by Django 5.0.2 on 2024-03-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_parcel_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryproof',
            name='proof_image',
        ),
    ]
