# Generated by Django 5.0.2 on 2024-03-31 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_remove_deliveryproof_proof_image'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='proof_image',
            field=models.ImageField(default=1, upload_to='delivery_proofs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
