# Generated by Django 5.0.2 on 2024-03-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_parcel_proof_image_alter_parcel_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproof',
            name='proof_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='Customers.parcel'),
            preserve_default=False,
        ),
    ]
